services:
    bot:
        container_name: requina-bot
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - DISCORD_TOKEN=$DISCORD_TOKEN
            - GENAI_KEY=$GENAI_KEY
